<?xml version="1.0"?>
<package format="3">
  <name>camera_info_plugin</name>
  <version>0.0.1</version>
  <description>Gazebo Ignition plugin to publish /camera_info from FOV and resolution</description>

  <maintainer email="wtlove876@gmail.com">Tao Wang</maintainer>
  <license>Apache-2.0</license>

  <!-- Build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- ROS 2 dependencies -->
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <!-- Ignition dependencies -->
  <depend>ignition-plugin1</depend>
  <depend>ignition-gazebo6</depend>
  <depend>ignition-sensors6</depend>
  <depend>ignition-transport11</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
